# Docker Services ($name:$type:$search_term)
# airflow:docker:airflow-webserver
open-webui:docker:open-webui
# logstash:docker:logstash
# elasticsearch:docker:elasticsearch
# kibana:docker:kibana

# Binary Services ($name:$type:$search_term)
#loki:binary:/usr/local/bin/loki
promtail:binary:/usr/local/bin/promtail
ollama:binary:/usr/local/bin/ollama
#logstash-8.5.3:binary:logstash-8.5.3
#elasticsearch-8.5.3:binary:elasticsearch-8.5.3/jdk/bin/java -Xms
#kibana-8.5.3:binary:/data/kibana/kibana-8.5.3
node-exporter:binary:/node_exporter

# System Services ($name:$type:$search_term)
grafana:system:grafana-server
prometheus:system:prometheus
# node-exporter:system:prometheus-node-exporter
#nginx:system:nginx
mysql:system:mysqld

# Version Checks ($name:$type:$command)
rsyslog:version:rsyslogd -v
openssl:version:openssl version
# python:version:python -V
python3:version:python3 -V
java:version:java -version
node.js:version:node --version
docker:version:docker --version
# nginx:version:nginx -v
mysql:version:mysql --version
# elasticsearch:version:curl -s http://localhost:9200
# redis:version:redis-cli --version
# go:version:go version
# rust:version:rustc --version
# perl:version:perl -v
# php:version:php -v
